export const ConfigKey = {
  MONGO_URI: 'MONGO_URI',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  FIREBASE_AUTH_DOMAIN: 'FIREBASE_AUTH_DOMAIN',
  FIREBASE_BUCKET_NAME: 'FIREBASE_BUCKET_NAME',
  FIREBASE_PROJECT_ID: 'FIREBASE_PROJECT_ID',
  FIREBASE_APP_ID: 'FIREBASE_APP_ID',
  FIREBASE_API_KEY: 'FIREBASE_API_KEY',
  FIREBASE_MESSAGING_SENDER_ID: 'FIREBASE_MESSAGING_SENDER_ID',
  FIREBASE_MEASUREMENT_ID: 'FIREBASE_MEASUREMENT_ID',
  FLASK_URL: 'FLASK_URL'
} as const;

export type ConfigKey = keyof typeof ConfigKey;
